### ISSUE TITLE
Install fails on Centos with 2015.07.1-12-g174049f built on MoarVM version 2015.07

### ISSUE THREAD

**Issue by mpapec** [tony-o/perl6-http-server-async#16]
panda install HTTP::Server::Async
==> Fetching HTTP::Server::Async
==> Building HTTP::Server::Async
Compiling lib/HTTP/Server/Async/Response.pm6 to mbc
Compiling lib/HTTP/Server/Async/Request.pm6 to mbc
Compiling lib/HTTP/Server/Async.pm6 to mbc
==> Testing HTTP::Server::Async
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/01_request.t:42

# Looks like you planned 12 tests, but ran 8
t/01_request.t ....................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/12 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/02_plugins.t:24

t/01_request.t ....................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/12 subtests Failed 2/2 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/03_statuscode.t:21

t/03_statuscode.t .................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/04_unbuffered_laggy_response.t:26

t/04_unbuffered_laggy_response.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/3 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/05_laggyrequest.t:20

t/05_laggyrequest.t ...............
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/06_responsetimeout.t:20
t/06_responsetimeout.t ............
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/07_chunkedrequestecho.t:21

t/07_chunkedrequestecho.t .........
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests
Too many positionals passed; expected 1 argument but got 2
  in block <unit> at t/09_unbuffer.t:36

# Looks like you planned 7 tests, but ran 3
t/09_unbuffer.t ...................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/7 subtests

Test Summary Report
-------------------
t/01_request.t                  (Wstat: 65280 Tests: 8 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 12 tests but ran 8.
t/02_plugins.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/03_statuscode.t               (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/04_unbuffered_laggy_response.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
t/05_laggyrequest.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/06_responsetimeout.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/07_chunkedrequestecho.t       (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
t/09_unbuffer.t                 (Wstat: 65280 Tests: 3 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 3.
Files=8, Tests=11, 19 wallclock secs ( 0.05 usr  0.02 sys + 17.31 cusr  0.99 csys = 18.37 CPU)
Result: FAIL
test stage failed for HTTP::Server::Async: Tests failed
  in method throw at /home/mpapec/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
  in method install at lib/Panda.pm:133
  in method resolve at lib/Panda.pm:218
  in sub MAIN at /home/mpapec/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:20
  in block <unit> at /home/mpapec/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:87

Failure Summary
----------------
HTTP::Server::Async
        *test stage failed for HTTP::Server::Async: Tests failed

**Comment by mpapec** [comment]
Works with 2015.07.1-151-g5ad8122 built on MoarVM version 2015.07-57-gec051f5

**Comment by tony-o** [comment]
The syntax has changed so if you're using it, make sure to check out the readme

Sent from a phone




On Thu, Aug 20, 2015 at 5:46 AM -0700, "mpapec" <notifications@github.com<mailto:notifications@github.com>> wrote:


Works with 2015.07.1-151-g5ad8122 built on MoarVM version 2015.07-57-gec051f5

-
