### ISSUE TITLE
HTTP::Server::Async!parse does not handle all legal header configurations.

### ISSUE THREAD

**Issue by daotoad** [tony-o/perl6-http-server-async#17]
The parse() method at line 120 (as of this writing) does not support all possible header formats.

It fails for repeated/duplicate headers and also for headers whose values are split across multiple lines.  See [HTTP spec, section 4.2.](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

The code `my %h           = @lines.map({ .split(':', 2).map({.trim}) });` is used to unpack headers.

Any lines with leading spaces need to be trimmed and concatenated with the preceding line.  This should be doable with a  boring-ish for loop and indexes.  There may be a sexier perl6y way to do the same, but I don't know it.

As for duplicated headers, there are a number of choices, keep using a hash and make your code append rather than overwrite duplicate values.  Also, you could make a hash-like type that handles these multiple values cases.

Furthermore, thanks for writing this.

**Comment by tony-o** [comment]
@daotoad I'll update this and push, thanks for bringing this up

**Comment by tony-o** [comment]
@daotoad this should work as expected now.
